name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your preferred Node version
      - run: npm install
      - run: npm run predeploy
      - run: npm run deploy